import type { DayKey, ExerciseDefinition, ExerciseSet, Workout, WorkoutExercise } from "../types";
import { EXERCISE_IMAGES } from "./exerciseImages";
import { EXERCISE_FOCUS } from "./exerciseFocus";

const rows: Array<[string, string, string, string, number, string, number, string, string]> = [
  ["barra-fixa-neutra","Barra fixa com pegada neutra","Costas","Peso corporal",4,"6",120,"Puxada vertical com o peso do corpo e pegada neutra.","Inicie com as escápulas, mantenha o corpo firme e suba sem impulso, mantendo as mãos em pegada neutra."],
  ["desenvolvimento-barra","Desenvolvimento com barra","Ombros","Barra",4,"10",90,"Press vertical com barra para os ombros. Pegada frontal ou posterior, em pé ou sentado.","Mantenha o abdômen ativo, estabilize o tronco e empurre a barra com controle."],
  ["rosca-alternada-em-pe","Rosca alternada em pé","Bíceps","Halteres",3,"10",60,"Rosca unilateral alternada realizada em pé.","Mantenha os cotovelos próximos ao tronco, alterne os braços e controle a descida."],
  ["rosca-inversa","Rosca inversa","Bíceps","Barra ou polia",3,"12",60,"Flexão de cotovelos com pegada pronada. Pode ser realizada na polia ou com barra.","Mantenha os cotovelos estáveis e os punhos alinhados durante todo o movimento."],
  ["crucifixo-inverso","Crucifixo inverso","Ombros","Livre ou máquina",3,"12",60,"Abertura posterior para deltoide posterior, livre ou na máquina.","Mantenha os ombros baixos e abra os braços de forma controlada, sem usar impulso."],
  ["remada-curvada-supinada","Remada curvada supinada","Costas","Barra ou aparelho",4,"10",90,"Remada inclinada com pegada supinada, realizada com barra ou aparelho.","Incline o tronco com coluna neutra e puxe em direção ao abdômen, mantendo o movimento controlado."],
  ["remada-cavalinho","Remada cavalinho","Costas","Livre ou máquina",4,"10",90,"Remada horizontal no estilo cavalinho, podendo ser realizada livre ou na máquina.","Mantenha o tronco firme e conduza os cotovelos para trás, controlando a volta."],
  ["hip-thrust", "Hip Thrust", "Glúteos", "Barra", 4, "12", 90, "Extensão de quadril com ênfase em glúteos.", "Apoie a parte superior das costas no banco, mantenha o queixo recolhido e suba até alinhar quadril e tronco."],
  ["elevacao-pelvica", "Elevação pélvica", "Glúteos", "Barra", 4, "12", 90, "Movimento de extensão de quadril feito no solo.", "Mantenha os pés firmes, contraia o abdômen e pause no topo sem hiperestender a lombar."],
  ["glute-bridge", "Glute Bridge", "Glúteos", "Peso corporal", 3, "15", 60, "Ponte de glúteos para ativação e controle.", "Deite-se, aproxime os calcanhares do quadril e eleve a pelve com controle."],
  ["coice", "Coice", "Glúteos", "Cabo", 3, "12", 60, "Extensão unilateral de quadril no cabo.", "Estabilize o tronco e mova a perna sem embalar o corpo."],
  ["abducao", "Abdução", "Glúteos", "Máquina", 3, "15", 60, "Abdução de quadril com resistência controlada.", "Mantenha o tronco estável e retorne devagar, sem deixar a carga bater."],
  ["agachamento-sumo", "Agachamento sumô", "Glúteos", "Halter", 3, "12", 90, "Agachamento com base ampla e pés apontados para fora.", "Desça entre os quadris mantendo joelhos alinhados com os pés."],
  ["agachamento", "Agachamento", "Pernas", "Barra", 4, "10", 120, "Agachamento multiarticular para membros inferiores.", "Tronco firme, pés estáveis e joelhos acompanhando a direção dos dedos."],
  ["leg-press", "Leg Press", "Pernas", "Máquina", 4, "12", 90, "Empurrada de pernas em máquina guiada.", "Desça até onde a pelve permaneça apoiada e empurre sem travar os joelhos."],
  ["hack", "Hack", "Pernas", "Máquina", 3, "10", 90, "Agachamento guiado no aparelho hack.", "Mantenha as costas apoiadas, controle a descida e evite travar os joelhos."],
  ["extensora", "Cadeira extensora", "Pernas", "Máquina", 3, "12", 60, "Extensão de joelho para quadríceps.", "Ajuste o eixo da máquina ao joelho e suba sem impulso."],
  ["flexora", "Cadeira flexora", "Pernas", "Máquina", 3, "12", 60, "Flexão de joelho para posteriores de coxa.", "Mantenha o quadril apoiado e controle a volta da carga."],
  ["stiff", "Stiff", "Posterior", "Barra", 4, "10", 90, "Hinge de quadril com foco em posteriores.", "Leve o quadril para trás, mantenha a coluna neutra e a barra próxima às pernas."],
  ["afundo", "Afundo", "Pernas", "Halteres", 3, "10", 90, "Movimento unilateral de membros inferiores.", "Dê um passo confortável e desça mantendo o tronco firme."],
  ["passada", "Passada", "Pernas", "Halteres", 3, "12", 90, "Passos alternados para força e estabilidade.", "Mantenha espaço entre os pés e controle cada troca de apoio."],
  ["panturrilha", "Panturrilha", "Pernas", "Máquina", 4, "15", 60, "Elevação dos calcanhares para panturrilhas.", "Use amplitude completa, pause no topo e desça com controle."],
  ["puxada-frontal", "Puxada frontal", "Costas", "Cabo", 4, "10", 75, "Puxada vertical para dorsais.", "Puxe em direção à parte alta do peito sem balançar o tronco."],
  ["remada-baixa", "Remada baixa", "Costas", "Cabo", 3, "12", 75, "Remada horizontal para costas.", "Inicie o movimento com as escápulas e mantenha o peito aberto."],
  ["remada-unilateral", "Remada unilateral", "Costas", "Halter", 3, "10", 75, "Remada unilateral apoiada.", "Mantenha o tronco estável e conduza o cotovelo para trás."],
  ["remada-curvada", "Remada curvada", "Costas", "Barra", 4, "8", 90, "Remada inclinada para costas.", "Incline o tronco com coluna neutra e puxe a barra em direção ao abdômen."],
  ["supino", "Supino", "Peito", "Barra", 4, "8", 90, "Press horizontal para peitoral.", "Mantenha os pés firmes e desça a barra com controle."],
  ["crucifixo", "Crucifixo", "Peito", "Halteres", 3, "12", 60, "Adução horizontal com ênfase no peitoral.", "Flexione levemente os cotovelos e use amplitude confortável."],
  ["crossover", "Crossover", "Peito", "Cabo", 3, "12", 60, "Adução de braços em cabos.", "Mantenha o tronco estável e aproxime as mãos sem perder o controle."],
  ["elevacao-lateral", "Elevação lateral", "Ombros", "Halteres", 3, "12", 60, "Elevação lateral para deltoides.", "Eleve os braços até a linha dos ombros sem usar impulso."],
  ["elevacao-frontal", "Elevação frontal", "Ombros", "Halteres", 3, "12", 60, "Elevação anterior dos braços.", "Suba até a altura dos ombros com punhos neutros."],
  ["desenvolvimento", "Desenvolvimento", "Ombros", "Halteres", 4, "10", 75, "Press vertical para ombros.", "Mantenha o abdômen ativo e empurre sem arquear a lombar."],
  ["rosca-direta", "Rosca direta", "Bíceps", "Barra", 3, "12", 60, "Flexão de cotovelos com barra.", "Mantenha os cotovelos próximos ao tronco e evite balançar."],
  ["rosca-alternada", "Rosca alternada", "Bíceps", "Halteres", 3, "10", 60, "Rosca unilateral alternada.", "Gire a palma na subida se for confortável e controle a descida."],
  ["rosca-martelo", "Rosca martelo", "Bíceps", "Halteres", 3, "12", 60, "Rosca com pegada neutra.", "Mantenha os punhos alinhados e os cotovelos estáveis."],
  ["triceps-pulley", "Tríceps pulley", "Tríceps", "Cabo", 3, "12", 60, "Extensão de cotovelos na polia.", "Fixe os cotovelos junto ao corpo e estenda sem projetar os ombros."],
  ["triceps-frances", "Tríceps francês", "Tríceps", "Halter", 3, "12", 60, "Extensão acima da cabeça para tríceps.", "Mantenha os cotovelos apontados para frente e mova os antebraços."],
  ["triceps-testa", "Tríceps testa", "Tríceps", "Barra", 3, "10", 60, "Extensão de cotovelos deitada.", "Desça a barra com controle, mantendo os braços estáveis."],
  ["abdominal", "Abdominal", "Abdômen", "Peso corporal", 3, "15", 45, "Flexão controlada do tronco.", "Expire ao subir e mantenha a lombar confortável."],
  ["prancha", "Prancha", "Abdômen", "Peso corporal", 3, "45", 45, "Isometria de estabilização do tronco.", "Alinhe cabeça, tronco e quadril e respire sem prender o ar."],
  ["elevacao-pernas", "Elevação de pernas", "Abdômen", "Peso corporal", 3, "12", 45, "Elevação controlada das pernas.", "Mantenha o abdômen ativo e evite arquear a lombar."],
  ["kickback-elastico", "Coice com elástico", "Glúteos", "Elástico", 3, "15", 60, "Extensão de quadril com resistência elástica.", "Prenda o elástico com segurança, mantenha o quadril alinhado e leve a perna para trás sem girar a pelve."],
  ["abducao-elastico", "Abdução com elástico", "Glúteos", "Elástico", 3, "20", 45, "Abdução de quadril com faixa elástica.", "Mantenha tensão constante no elástico e afaste os joelhos sem inclinar o tronco."],
  ["glute-bridge-elastico", "Ponte de glúteo com elástico", "Glúteos", "Elástico", 3, "15", 60, "Ponte de quadril com resistência nos joelhos.", "Empurre os joelhos levemente para fora e faça uma pausa no topo do movimento."],
  ["agachamento-bulgaro", "Agachamento búlgaro", "Pernas", "Halteres", 3, "10", 90, "Agachamento unilateral com o pé traseiro apoiado.", "Use uma base estável, desça verticalmente e mantenha o joelho da frente alinhado ao pé."],
  ["agachamento-frontal", "Agachamento frontal", "Pernas", "Barra", 4, "8", 120, "Agachamento com a barra posicionada à frente dos ombros.", "Mantenha os cotovelos altos, o tronco firme e desça apenas até preservar a postura."],
  ["agachamento-goblet", "Agachamento goblet", "Pernas", "Halter", 3, "12", 90, "Agachamento segurando um peso junto ao peito.", "Segure o halter próximo ao corpo e empurre o chão mantendo os joelhos acompanhando os pés."],
  ["step-up", "Step-up", "Pernas", "Peso corporal", 3, "10", 75, "Subida em plataforma para força unilateral.", "Apoie todo o pé na plataforma e suba usando principalmente a perna que está em cima."],
  ["mesa-flexora", "Mesa flexora", "Posterior", "Máquina", 3, "12", 60, "Flexão de joelhos deitado na máquina.", "Ajuste o rolo acima dos calcanhares, mantenha o quadril apoiado e controle a descida."],
  ["good-morning", "Good morning", "Posterior", "Barra", 3, "10", 90, "Dobradiça de quadril com barra apoiada nas costas.", "Flexione levemente os joelhos, leve o quadril para trás e mantenha a coluna neutra."],
  ["levantamento-terra", "Levantamento terra", "Posterior", "Barra", 4, "6", 150, "Levantamento do solo com extensão de quadril e joelhos.", "Mantenha a barra próxima às pernas, firme o abdômen e não arredonde a lombar."],
  ["terra-sumo", "Levantamento terra sumô", "Pernas", "Barra", 4, "6", 150, "Levantamento com base ampla e maior participação dos adutores.", "Abra os pés confortavelmente, empurre o chão e mantenha a barra próxima ao corpo."],
  ["panturrilha-sentado", "Panturrilha sentado", "Pernas", "Máquina", 4, "15", 60, "Flexão plantar sentado com ênfase no sóleo.", "Desça o calcanhar com controle e faça uma pausa no ponto alto."],
  ["panturrilha-unilateral", "Panturrilha unilateral", "Pernas", "Peso corporal", 3, "15", 45, "Elevação de calcanhar em um apoio.", "Use uma parede para equilíbrio e complete a amplitude sem saltar."],
  ["pullover-cabo", "Pullover na polia", "Costas", "Cabo", 3, "12", 60, "Extensão de ombro na polia para dorsais.", "Mantenha os braços levemente flexionados e puxe a barra até as coxas sem balançar."],
  ["puxada-neutra", "Puxada neutra", "Costas", "Cabo", 4, "10", 75, "Puxada vertical com pegada neutra.", "Conduza os cotovelos para baixo e evite compensar com a lombar."],
  ["barra-fixa", "Barra fixa", "Costas", "Peso corporal", 4, "6", 120, "Puxada vertical com o peso do corpo.", "Inicie com as escápulas, mantenha o corpo firme e suba sem impulso."],
  ["remada-maquina", "Remada articulada", "Costas", "Máquina", 3, "10", 75, "Remada sentada em máquina guiada.", "Apoie o peito quando houver suporte e aproxime as escápulas com controle."],
  ["face-pull", "Face pull", "Costas", "Cabo", 3, "15", 60, "Puxada para a face com foco na parte superior das costas.", "Puxe a corda na direção do rosto, abrindo os cotovelos e mantendo os ombros baixos."],
  ["encolhimento", "Encolhimento de ombros", "Costas", "Halteres", 3, "12", 60, "Elevação dos ombros para trapézio.", "Eleve os ombros verticalmente sem fazer círculos e retorne devagar."],
  ["supino-inclinado", "Supino inclinado", "Peito", "Halteres", 4, "10", 90, "Press inclinado com maior participação da porção clavicular do peitoral.", "Mantenha as escápulas apoiadas, desça os halteres com controle e não bata os pesos."],
  ["supino-maquina", "Supino na máquina", "Peito", "Máquina", 3, "12", 75, "Press horizontal guiado para peitoral.", "Ajuste o banco para as mãos ficarem na linha média do peito e empurre sem travar os cotovelos."],
  ["flexao", "Flexão de braços", "Peito", "Peso corporal", 3, "10", 60, "Press horizontal com o peso do corpo.", "Mantenha o corpo alinhado e desça aproximando o peito do chão sem perder a posição."],
  ["flexao-inclinada", "Flexão inclinada", "Peito", "Peso corporal", 3, "12", 45, "Variação de flexão com as mãos elevadas.", "Use uma superfície firme e mantenha o tronco alinhado durante todo o movimento."],
  ["crucifixo-maquina", "Peck deck", "Peito", "Máquina", 3, "12", 60, "Adução horizontal dos braços na máquina.", "Mantenha o peito aberto e aproxime os braços sem deixar a carga bater."],
  ["desenvolvimento-maquina", "Desenvolvimento na máquina", "Ombros", "Máquina", 3, "10", 75, "Press vertical guiado para os ombros.", "Ajuste o banco, mantenha as costas apoiadas e empurre sem elevar os ombros."],
  ["elevacao-lateral-cabo", "Elevação lateral no cabo", "Ombros", "Cabo", 3, "12", 60, "Abdução do ombro com resistência contínua.", "Comece com o cabo cruzado à frente do corpo e eleve até uma altura confortável."],
  ["posterior-maquina", "Voador inverso", "Ombros", "Máquina", 3, "15", 60, "Abertura posterior para deltoide posterior.", "Mantenha os ombros baixos e abra os braços sem usar impulso."],
  ["rosca-scott", "Rosca Scott", "Bíceps", "Máquina", 3, "12", 60, "Flexão de cotovelo com os braços apoiados.", "Mantenha os braços apoiados e não estenda completamente os cotovelos sob carga."],
  ["rosca-cabo", "Rosca na polia", "Bíceps", "Cabo", 3, "12", 60, "Rosca com tensão contínua da polia.", "Mantenha o tronco parado e mova apenas os antebraços."],
  ["rosca-elastico", "Rosca com elástico", "Bíceps", "Elástico", 3, "15", 45, "Flexão de cotovelos com faixa elástica.", "Pise no centro do elástico, mantenha os cotovelos junto ao corpo e controle a volta."],
  ["triceps-corda", "Tríceps corda", "Tríceps", "Cabo", 3, "12", 60, "Extensão de cotovelos usando corda.", "Separe as pontas no final e mantenha os cotovelos estáveis ao lado do corpo."],
  ["triceps-coice", "Tríceps coice", "Tríceps", "Halteres", 3, "12", 60, "Extensão de cotovelo com o tronco inclinado.", "Fixe o braço acima do cotovelo e estenda o antebraço sem girar o ombro."],
  ["mergulho-banco", "Tríceps no banco", "Tríceps", "Peso corporal", 3, "10", 75, "Extensão de cotovelos com apoio no banco.", "Mantenha os ombros longe das orelhas e desça somente até onde o ombro ficar confortável."],
  ["abdominal-cabo", "Abdominal na polia", "Abdômen", "Cabo", 3, "15", 45, "Flexão de tronco resistida na polia.", "Enrole o tronco levando as costelas em direção à pelve, sem puxar com os braços."],
  ["abdominal-roda", "Abdominal com roda", "Abdômen", "Roda abdominal", 3, "8", 75, "Anti-extensão do tronco com roda abdominal.", "Comece com amplitude curta e mantenha glúteos e abdômen contraídos."],
  ["dead-bug", "Dead bug", "Abdômen", "Peso corporal", 3, "10", 45, "Estabilização lombo-pélvica no solo.", "Mantenha a lombar próxima ao chão e mova braços e pernas lentamente."],
  ["bird-dog", "Bird dog", "Abdômen", "Peso corporal", 3, "10", 45, "Estabilização contralateral do tronco.", "Estenda braço e perna opostos sem girar a pelve e retorne com controle."],
  ["prancha-lateral", "Prancha lateral", "Abdômen", "Peso corporal", 3, "30", 45, "Isometria lateral para oblíquos e estabilizadores.", "Mantenha o corpo em linha e eleve o quadril sem deixar o tronco girar."],
  ["mountain-climber", "Mountain climber", "Condicionamento", "Peso corporal", 3, "30s", 45, "Movimento dinâmico de condicionamento com apoio das mãos.", "Mantenha os ombros sobre as mãos e alterne os joelhos sem perder a estabilidade do tronco."],
  ["polichinelo", "Polichinelo", "Condicionamento", "Peso corporal", 3, "30s", 30, "Exercício cíclico de corpo inteiro para aquecimento e condicionamento.", "Aterrisse suavemente, mantenha ritmo confortável e reduza o impacto se necessário."],
  ["burpee", "Burpee", "Condicionamento", "Peso corporal", 3, "10", 60, "Sequência de agachamento e apoio frontal que combina transições rápidas de corpo inteiro para condicionamento.", "Agache e apoie as mãos no chão, leve os pés para trás em prancha, retorne sob o quadril e fique em pé com controle."],
  ["pular-corda", "Pular corda", "Condicionamento", "Corda", 3, "60s", 30, "Saltos baixos e repetidos com rotação de corda para desenvolver resistência cardiorrespiratória e coordenação.", "Mantenha os cotovelos próximos ao corpo, gire a corda pelos punhos e faça saltos curtos com aterrissagem leve."],
  ["corrida-estacionaria", "Corrida estacionária com joelhos altos", "Condicionamento", "Peso corporal", 3, "30s", 30, "Corrida no mesmo lugar alternando elevação dos joelhos e balanço dos braços para elevar a frequência cardíaca.", "Mantenha o tronco ereto, alterne os joelhos sem perder o equilíbrio e ajuste a altura e o ritmo ao seu condicionamento."],
  ["caminhada-elastico", "Caminhada lateral com elástico", "Glúteos", "Elástico", 3, "12 passos", 45, "Passos laterais com tensão contínua nos abdutores.", "Mantenha os joelhos alinhados e dê passos curtos sem deixar o elástico perder tensão."],
  ["levantamento-lateral-caneleira", "Elevação lateral de perna", "Glúteos", "Caneleira", 3, "15", 45, "Abdução de quadril com caneleira ou peso leve.", "Apoie-se com estabilidade, mantenha a ponta do pé neutra e eleve sem inclinar o tronco."],
  ["curl-inclinado-halteres","Rosca inclinada com halteres","Bíceps","Halteres",3,"10",60,"Rosca realizada em banco inclinado para trabalhar os bíceps com os braços posicionados atrás do tronco.","Mantenha os ombros apoiados, cotovelos estáveis e suba os halteres sem balançar."],
  ["rosca-concentrada-halter","Rosca concentrada","Bíceps","Halter",3,"12",60,"Flexão unilateral do cotovelo com o braço apoiado na coxa.","Apoie o braço, mantenha o ombro parado e controle completamente a descida."],
  ["rosca-martelo-halteres","Rosca martelo com halteres","Bíceps","Halteres",3,"12",60,"Rosca com pegada neutra, enfatizando bíceps, braquial e braquiorradial.","Mantenha as palmas voltadas uma para a outra e os cotovelos próximos ao corpo."],
  ["rosca-concentrada-polia","Rosca concentrada na polia","Bíceps","Cabo",3,"12",60,"Rosca unilateral com tensão contínua da polia.","Mantenha o braço fixo e faça a flexão do cotovelo sem girar o tronco."],
  ["rosca-scott-barra","Rosca Scott com barra","Bíceps","Barra",3,"10",60,"Rosca com os braços apoiados no banco Scott.","Apoie os braços, evite estender completamente os cotovelos sob carga e controle a volta."],
  ["rosca-unilateral-polia","Rosca unilateral na polia","Bíceps","Cabo",3,"12",60,"Rosca de um braço com resistência contínua da polia.","Mantenha o cotovelo junto ao corpo e execute cada lado com controle."],
  ["elevacao-borboleta","Elevação borboleta para ombros","Ombros","Halteres",3,"12",60,"Elevação lateral com os cotovelos flexionados, mantendo a posição dos braços durante o movimento.","Mantenha os cotovelos dobrados, eleve lateralmente até a linha dos ombros e retorne devagar."],
  ["elevacao-lateral-frontal-elastico","Elevação lateral e frontal com elástico","Ombros","Elástico",3,"12",60,"Variação que combina elevação lateral e frontal com resistência elástica.","Mantenha o tronco firme e execute as duas trajetórias sem usar impulso."],
  ["elevacao-frontal-elastico","Elevação frontal com elástico","Ombros","Elástico",3,"12",60,"Elevação anterior dos braços usando resistência elástica.","Suba até uma altura confortável e mantenha os ombros baixos."],
  ["crucifixo-inverso-elastico","Crucifixo inverso com elástico","Ombros","Elástico",3,"15",60,"Abertura posterior dos braços para deltoide posterior.","Mantenha a tensão no elástico e abra os braços sem elevar os ombros."],
  ["desenvolvimento-elastico","Desenvolvimento de ombros com elástico","Ombros","Elástico",3,"12",60,"Press vertical usando resistência elástica.","Mantenha o abdômen firme e pressione acima da cabeça sem arquear a lombar."],
  ["desenvolvimento-arnold","Desenvolvimento Arnold","Ombros","Halteres",3,"10",75,"Press de ombros com rotação controlada dos antebraços.","Comece com as palmas voltadas para você e gire durante a subida, mantendo o tronco estável."],
  ["remada-deltoide-posterior-elastico","Remada para deltoide posterior com elástico","Ombros","Elástico",3,"15",60,"Remada com foco no deltoide posterior e controle escapular.","Puxe com os cotovelos e mantenha os ombros afastados das orelhas."],
  ["supino-halteres","Supino com halteres","Peito","Halteres",4,"10",90,"Press horizontal com halteres para o peitoral.","Mantenha os pés firmes, desça os halteres com controle e empurre sem bater os pesos."],
  ["supino-inclinado-barra","Supino inclinado com barra","Peito","Barra",4,"8",90,"Press em banco inclinado com maior participação da região clavicular do peitoral.","Mantenha as escápulas apoiadas e desça a barra de forma controlada."],
  ["supino-declinado-barra","Supino declinado com barra","Peito","Barra",4,"8",90,"Press em banco declinado para o peitoral.","Mantenha a posição estável no banco e controle a descida da barra."],
  ["crucifixo-halteres","Crucifixo com halteres","Peito","Halteres",3,"12",60,"Adução horizontal dos braços com leve flexão dos cotovelos.","Mantenha os cotovelos levemente flexionados e não desça além da amplitude confortável."],
  ["flexao-bracos","Flexão de braços","Peito","Peso corporal",3,"12",60,"Press horizontal com o peso corporal.","Mantenha cabeça, tronco e quadril alinhados e controle a descida."],
  ["puxada-fechada-elastico","Puxada fechada com elástico","Costas","Elástico",3,"12",60,"Puxada vertical com pegada fechada usando resistência elástica.","Puxe os cotovelos para baixo e mantenha o tronco estável."],
  ["puxada-supinada-elastico","Puxada supinada com elástico","Costas","Elástico",3,"12",60,"Puxada vertical com pegada supinada.","Mantenha os cotovelos próximos ao corpo e evite compensar com a lombar."],
  ["puxada-unilateral-polia","Puxada unilateral na polia","Costas","Cabo",3,"10",75,"Puxada vertical de um braço para trabalhar as dorsais unilateralmente.","Conduza o cotovelo para baixo e mantenha o ombro controlado."],
  ["puxada-barra-lateral","Puxada lateral com barra na polia","Costas","Cabo",3,"10",75,"Variação de puxada com barra lateral na polia.","Mantenha o peito aberto e puxe sem inclinar excessivamente o tronco."],
  ["puxada-barra-v","Puxada com barra V","Costas","Cabo",3,"10",75,"Puxada vertical com pegada paralela usando barra V.","Leve os cotovelos para baixo e controle o retorno da carga."],
  ["pullover-barra","Pullover com barra","Costas","Barra",3,"12",60,"Extensão do ombro em movimento de pullover para dorsais.","Mantenha os braços controlados e não force a amplitude do ombro."],
  ["pullover-barra-bracos-dobrados","Pullover com barra e braços dobrados","Costas","Barra",3,"12",60,"Variação de pullover mantendo os cotovelos flexionados.","Mantenha os cotovelos levemente dobrados e mova os braços de forma controlada."],
  ["pulldown-bracos-retos-corda","Pulldown com braços retos e corda","Costas","Cabo",3,"12",60,"Extensão de ombros na polia com braços quase estendidos.","Mantenha o abdômen firme e puxe a corda até a linha das coxas."],
  ["remada-alta-polia-v","Remada alta na polia com barra V","Costas","Cabo",3,"12",75,"Remada horizontal/alta usando barra V.","Puxe os cotovelos para trás mantendo o peito aberto e sem balançar o tronco."],
  ["agachamento-frontal-banco","Agachamento frontal com barra para banco","Pernas","Barra",3,"10",90,"Variação de agachamento frontal usando banco como referência de amplitude.","Mantenha os cotovelos altos, tronco firme e desça com controle até o banco."],
  ["agachamento-goblet-halter","Agachamento goblet com halter","Pernas","Halter",3,"12",90,"Agachamento segurando o halter junto ao peito.","Mantenha o peso próximo ao corpo e acompanhe os joelhos na direção dos pés."],
  ["extensora-maquina","Cadeira extensora na máquina","Pernas","Máquina",3,"12",60,"Extensão de joelho guiada para quadríceps.","Ajuste o eixo da máquina ao joelho e estenda sem usar impulso."],
  ["sissy-squat","Sissy squat","Pernas","Peso corporal",3,"10",75,"Variação de agachamento com forte demanda de quadríceps e controle corporal.","Use apoio se necessário e mantenha a amplitude dentro do seu controle."],
  ["good-morning-barra","Good morning com barra","Posterior","Barra",3,"10",90,"Dobradiça de quadril com barra apoiada nos ombros.","Leve o quadril para trás, mantenha a coluna neutra e suba usando os extensores do quadril."],
  ["terra-pernas-retas","Levantamento terra com pernas retas","Posterior","Barra",4,"8",120,"Hinge de quadril com maior alongamento dos posteriores.","Mantenha a barra próxima às pernas e pare antes de perder a posição neutra da coluna."],
  ["flexora-halter-deitado","Flexora com halter deitado","Posterior","Halter",3,"12",60,"Flexão de joelho deitado segurando um halter de forma segura.","Mantenha o quadril estável e flexione os joelhos sem tirar a pelve do apoio."],
  ["nordico-assistido-polia","Flexão nórdica assistida na polia","Posterior","Cabo",3,"8",90,"Variação assistida do movimento nórdico para posteriores de coxa.","Controle a descida e use a assistência para retornar mantendo o quadril alinhado."],
  ["hip-thrust-elastico-ajoelhado","Hip thrust com elástico ajoelhado","Glúteos","Elástico",3,"15",60,"Extensão de quadril com resistência elástica na posição ajoelhada.","Contraia os glúteos no final e evite hiperestender a lombar."],
  ["glute-bridge-barra-banco","Ponte de glúteos com barra no banco","Glúteos","Barra",4,"12",90,"Ponte de glúteos com apoio dos pés no banco e carga externa.","Eleve a pelve com controle e pause no topo mantendo as costelas controladas."],
  ["terra-sumo-barra","Levantamento terra sumô com barra","Glúteos","Barra",4,"6",120,"Levantamento com base ampla e grande participação de glúteos e adutores.","Abra os pés, mantenha a barra próxima e empurre o chão sem arredondar a lombar."],
  ["triceps-overhead-corda","Tríceps acima da cabeça com corda","Tríceps","Cabo",3,"12",60,"Extensão de cotovelos acima da cabeça usando corda.","Mantenha os cotovelos apontados para frente e estenda sem mover excessivamente os ombros."],
  ["triceps-overhead-barra-sentado","Tríceps acima da cabeça com barra sentado","Tríceps","Barra",3,"10",60,"Extensão de cotovelos acima da cabeça em posição sentada.","Mantenha o tronco apoiado e os cotovelos estáveis durante a extensão."],
  ["flexao-fechada-elastico","Flexão fechada com elástico","Tríceps","Elástico",3,"10",60,"Flexão com mãos mais próximas e resistência elástica.","Mantenha os cotovelos próximos ao tronco e o corpo alinhado."],
  ["triceps-coice-polia","Tríceps coice na polia","Tríceps","Cabo",3,"12",60,"Extensão de cotovelo unilateral ou alternada com polia.","Fixe o braço e estenda o antebraço sem girar o ombro."],
  ["bicicleta-abdominal","Bicicleta abdominal","Abdômen","Peso corporal",3,"20",45,"Movimento alternado de flexão de tronco e quadril para o abdômen.","Mantenha a lombar confortável e faça a rotação do tronco de forma controlada."],
  ["russian-twist-assistido","Russian twist assistido","Abdômen","Peso corporal",3,"16",45,"Rotação controlada do tronco em posição sentada.","Mantenha o peito aberto, controle a rotação e evite movimentos bruscos."],
  ["elevacao-joelhos-barra-assistida","Elevação de joelhos na barra assistida","Abdômen","Peso corporal",3,"12",60,"Elevação dos joelhos com assistência para controlar o movimento.","Evite balançar o corpo e eleve os joelhos usando o controle do abdômen."],
  ["bicicleta-abdominal-elastico","Bicicleta abdominal com elástico","Abdômen","Elástico",3,"20",45,"Variação da bicicleta abdominal com resistência elástica.","Mantenha a pelve estável e execute as alternâncias de forma controlada."],
  ["prancha-lateral-inclinada","Prancha lateral inclinada","Abdômen","Peso corporal",3,"30s",45,"Isometria lateral com apoio elevado para ajustar a dificuldade.","Mantenha o corpo alinhado e não deixe o quadril cair."],
  ["elevacao-pernas-assistida","Elevação de pernas assistida","Abdômen","Peso corporal",3,"12",60,"Elevação das pernas assistida para controlar a amplitude.","Mantenha o abdômen ativo e evite arquear excessivamente a lombar."],
  ["panturrilha-halteres-em-pe","Panturrilha em pé com halteres","Pernas","Halteres",4,"15",60,"Flexão plantar em pé segurando halteres.","Use amplitude confortável, pause no topo e desça lentamente."],
  ["panturrilha-halter-sentado","Panturrilha sentado com halter","Pernas","Halter",4,"15",60,"Flexão plantar sentado com carga sobre as coxas.","Desça os calcanhares com controle e faça uma contração forte no topo."],
  ["panturrilha-elastico-unilateral","Panturrilha unilateral com elástico","Pernas","Elástico",3,"15",45,"Elevação unilateral dos calcanhares usando elástico.","Mantenha o equilíbrio e complete a amplitude sem saltar."],
  ["panturrilha-burro","Panturrilha estilo burro","Pernas","Peso corporal",3,"15",45,"Elevação dos calcanhares com o tronco inclinado.","Mantenha os pés estáveis e faça o movimento pelo tornozelo."],
  ["encolhimento-elastico","Encolhimento com elástico","Costas","Elástico",3,"15",60,"Elevação vertical dos ombros contra resistência elástica.","Eleve os ombros sem fazer círculos e retorne lentamente."],
  ["fundos-escapulares","Fundos escapulares","Costas","Peso corporal",3,"12",60,"Movimento de depressão e elevação escapular com os cotovelos estáveis.","Mova principalmente as escápulas e mantenha o corpo controlado."],
  ["caminhada-inclinada-esteira","Caminhada na esteira inclinada","Condicionamento","Esteira",3,"10min",60,"Caminhada em esteira com inclinação para aumentar a demanda cardiorrespiratória.","Mantenha postura confortável, ritmo sustentável e use o apoio somente quando necessário."],
  ["joelho-alto-parede","Elevação de joelho contra a parede","Condicionamento","Peso corporal",3,"30s",30,"Movimento unilateral de elevação do joelho para coordenação e condicionamento.","Mantenha o tronco firme e eleve o joelho com controle, ajustando a velocidade ao seu nível."],
  ["3-4-sit-up","Abdominal 3/4 Sit-Up","Abdômen","Peso corporal",3,"12",45,"Variação de abdominal com amplitude controlada, parando antes da subida completa.","Mantenha o abdômen contraído, suba de forma controlada e evite puxar o pescoço."],
  ["alternate-heel-touchers","Toque alternado nos calcanhares","Abdômen","Peso corporal",3,"20",45,"Flexão lateral alternada do tronco para trabalhar principalmente os oblíquos.","Mantenha os ombros levemente elevados e alcance cada calcanhar sem tirar o controle da lombar."],
  ["band-alternating-v-up","V-Up alternado com elástico","Abdômen","Elástico",3,"12",45,"Variação unilateral do V-up com resistência elástica.","Mantenha o movimento controlado e evite compensar com impulso."],
  ["band-jack-knife-sit-up","Jackknife abdominal com elástico","Abdômen","Elástico",3,"12",45,"Movimento de fechamento do tronco e pernas com resistência elástica.","Ative o abdômen antes de aproximar mãos e pernas e controle a volta."],
  ["barbell-press-sit-up","Abdominal com pressão de barra","Abdômen","Barra",3,"10",60,"Sit-up combinado com pressão da barra para aumentar a demanda do core.","Use carga leve, mantenha os pés firmes e controle tanto a subida quanto a descida."],
  ["cable-reverse-crunch","Abdominal reverso na polia","Abdômen","Cabo",3,"12",60,"Flexão reversa do tronco/pelve contra resistência da polia.","Enrole a pelve em direção ao tronco sem balançar as pernas."],
  ["cable-seated-crunch","Abdominal sentado na polia","Abdômen","Cabo",3,"15",45,"Flexão de tronco sentado com resistência contínua da polia.","Arredonde o tronco de forma controlada e não puxe a carga apenas com os braços."],
  ["lever-seated-crunch-chest-pad","Abdominal na máquina com apoio de peito","Abdômen","Máquina",3,"12",60,"Abdominal guiado em máquina com apoio do peito para estabilizar o movimento.","Ajuste o equipamento, contraia o abdômen e faça a flexão sem usar impulso."],
  ["lever-seated-crunch-v-2","Abdominal sentado na máquina — Variação 2","Abdômen","Máquina",3,"12",60,"Variação do abdominal sentado em máquina guiada.","Mantenha o quadril estável e concentre o movimento na flexão do tronco."],
  ["lever-seated-leg-raise-crunch","Elevação de pernas + abdominal na máquina","Abdômen","Máquina",3,"10",60,"Combinação guiada de elevação das pernas e flexão do tronco.","Controle as duas fases do movimento e evite acelerar para vencer a carga."],
  ["lever-kneeling-twist","Rotação ajoelhada na máquina","Abdômen","Máquina",3,"12",60,"Rotação controlada do tronco em aparelho guiado, com foco nos oblíquos.","Mantenha o quadril estável e faça a rotação com amplitude confortável."],
  ["skater-hops","Saltos de patinador","Condicionamento","Peso corporal",3,"30s",30,"Saltos laterais alternados para elevar a frequência cardíaca e trabalhar coordenação.","Aterrisse com controle, use os braços para equilibrar e mantenha o ritmo sustentável."],
  ["ski-step","Ski step","Condicionamento","Peso corporal",3,"30s",30,"Deslocamento alternado semelhante ao gesto do esqui para condicionamento.","Mantenha o tronco firme e alterne os lados com aterrissagens leves."],
  ["scissor-jumps-male","Saltos tesoura","Condicionamento","Peso corporal",3,"30s",30,"Saltos alternados com troca das pernas para condicionamento e coordenação.","Aterre suavemente e mantenha o ritmo sem perder a estabilidade."],
  ["semi-squat-jump-male","Salto a partir do meio agachamento","Condicionamento","Peso corporal",3,"12",45,"Saltos repetidos iniciados em meio agachamento para potência e cardio.","Flexione os joelhos na aterrissagem e mantenha o tronco controlado."],
  ["star-jump-male","Salto estrela","Condicionamento","Peso corporal",3,"30s",30,"Salto de corpo inteiro com abertura simultânea de braços e pernas.","Faça aterrissagens suaves e ajuste a amplitude ao seu condicionamento."],
  ["short-stride-run","Corrida de passada curta","Condicionamento","Peso corporal",3,"30s",30,"Corrida rápida com passadas curtas para elevar a frequência cardíaca.","Mantenha postura ereta, passos rápidos e ritmo que consiga sustentar."],
  ["walk-elliptical-cross-trainer","Caminhada no elíptico","Condicionamento","Elíptico",3,"10min",60,"Cardio contínuo em aparelho elíptico, com baixo impacto nas articulações.","Mantenha postura ereta, ritmo constante e aumente a resistência gradualmente."],
  ["walking-on-stepmill","Subida no simulador de escadas","Condicionamento","Simulador de escadas",3,"10min",60,"Cardio contínuo no simulador de escadas para resistência e condicionamento.","Mantenha o peso distribuído nos pés e use as mãos apenas para equilíbrio quando necessário."],
  ["run-equipment","Corrida na esteira","Condicionamento","Esteira",3,"10min",60,"Corrida contínua em esteira para desenvolver resistência cardiorrespiratória.","Comece em velocidade confortável, mantenha postura estável e ajuste a intensidade progressivamente."],
  ["rotacao-externa-cabo","Rotação externa de ombro no cabo","Manguito rotador","Cabo",3,"15",45,"Rotação externa do ombro contra resistência do cabo, com foco nos músculos do manguito rotador.","Mantenha o cotovelo junto ao corpo, antebraço próximo de 90 graus e gire a mão para fora sem afastar o cotovelo do tronco."],
  ["rotacao-interna-cabo","Rotação interna de ombro no cabo","Manguito rotador","Cabo",3,"15",45,"Rotação interna do ombro contra resistência do cabo, trabalhando principalmente o subescapular e os estabilizadores do ombro.","Mantenha o cotovelo fixo junto ao corpo e gire o antebraço para dentro com amplitude confortável, sem compensar com o tronco."],
  ["rotacao-externa-halter-deitado","Rotação externa de ombro deitado com halter","Manguito rotador","Halter",3,"12",45,"Rotação externa do ombro realizada deitado de lado, com baixa carga e foco no controle do movimento.","Apoie o cotovelo junto ao corpo, mantenha o braço estável e gire o antebraço para cima lentamente."],
  ["rotacao-externa-halter-em-pe","Rotação externa de ombro com halter","Manguito rotador","Halter",3,"12",45,"Rotação externa do ombro com halter, realizada com o cotovelo estabilizado junto ao tronco.","Use carga leve, mantenha o cotovelo fixo e faça a rotação lentamente, sem projetar o ombro para frente."],
  ["supino-landmine-ajoelhado", "Supino landmine ajoelhado", "Peito", "Barra / Landmine", 3, "10", 90, "Press de peitoral realizado ajoelhado com a extremidade livre da barra em um sistema landmine, com trajetória diagonal para cima e para frente.", "Ajoelhe-se com o tronco ereto, segure a extremidade da barra junto ao alto do peito e pressione para cima e à frente até quase estender os braços; retorne devagar mantendo o abdômen firme."],
];

export const EXERCISE_CATALOG: ExerciseDefinition[] = rows.map(([id, name, muscle, equipment, defaultSets, defaultReps, defaultRestSeconds, description, instructions]) => ({
  id, name, muscle, equipment, defaultSets, defaultReps, defaultRestSeconds, description, instructions, imageUrl: EXERCISE_IMAGES[id], purpose: EXERCISE_FOCUS[id as keyof typeof EXERCISE_FOCUS]?.purpose ?? description, primaryMuscles: EXERCISE_FOCUS[id as keyof typeof EXERCISE_FOCUS]?.primaryMuscles ?? [muscle], secondaryMuscles: EXERCISE_FOCUS[id as keyof typeof EXERCISE_FOCUS]?.secondaryMuscles ?? [],
}));

export const DAYS: Array<{ key: DayKey; label: string; short: string }> = [
  { key: "seg", label: "Segunda-feira", short: "SEG" },
  { key: "ter", label: "Terça-feira", short: "TER" },
  { key: "qua", label: "Quarta-feira", short: "QUA" },
  { key: "qui", label: "Quinta-feira", short: "QUI" },
  { key: "sex", label: "Sexta-feira", short: "SEX" },
  { key: "sab", label: "Sábado", short: "SÁB" },
  { key: "dom", label: "Domingo", short: "DOM" },
];

export const WORKOUT_COLORS = ["#b8f32b", "#75bd26", "#39a77a", "#38a9c2", "#9478e8", "#e38d36"];

export function makeId(prefix = "bf"): string {
  return `${prefix}-${globalThis.crypto?.randomUUID?.() ?? `${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 9)}`}`;
}

export function makeWorkoutExercise(definition: ExerciseDefinition): WorkoutExercise {
  const sets: ExerciseSet[] = Array.from({ length: Math.min(10, Math.max(1, definition.defaultSets)) }, () => ({
    id: makeId("set"), reps: definition.defaultReps, weight: "", method: "Repetições", seconds: 45,
  }));
  return { ...definition, sets, restSeconds: definition.defaultRestSeconds, note: "" };
}

export function makeStarterWorkouts(): Workout[] {
  const get = (id: string) => EXERCISE_CATALOG.find((item) => item.id === id)!;
  const now = new Date().toISOString();
  const starters: Array<{ title: string; description: string; days: DayKey[]; color: string; exercises: string[] }> = [
    { title: "Treino A", description: "Glúteos + posterior", days: ["seg"], color: WORKOUT_COLORS[0], exercises: ["hip-thrust", "stiff", "flexora", "abducao"] },
    { title: "Treino B", description: "Pernas completas", days: ["qua"], color: WORKOUT_COLORS[2], exercises: ["agachamento", "leg-press", "extensora", "panturrilha"] },
    { title: "Treino C", description: "Superior + postura", days: ["sex"], color: WORKOUT_COLORS[3], exercises: ["puxada-frontal", "remada-baixa", "supino", "elevacao-lateral"] },
  ];
  return starters.map((item) => ({
    id: makeId("workout"), title: item.title, description: item.description, days: item.days, color: item.color,
    exercises: item.exercises.map((id) => makeWorkoutExercise(get(id))), createdAt: now, updatedAt: now,
  }));
}
