import { exerciseImageUrl } from "./assetPaths";

const manuscriptImages: Record<string, string> = {
  "barra-fixa-neutra": "https://static.exercisedb.dev/media/pP8wP2P.gif",
  "desenvolvimento-barra": "https://d3d2ynhodh9o1z.cloudfront.net/exercises/barbell-seated-overhead-press.gif",
  "rosca-alternada-em-pe": "/manus-storage/rosca-alternada_99315757.gif",
  "rosca-inversa": "https://media.giphy.com/media/19sC5eqKESXu3Adk6l/giphy.gif",
  "crucifixo-inverso": "https://d3d2ynhodh9o1z.cloudfront.net/exercises/dumbbell-reverse-fly.gif",
  "remada-curvada-supinada": "https://media.giphy.com/media/UrWHv8duIA6ztuR6ks/giphy.gif",
  "remada-cavalinho": "https://gifdb.com/gif/animated-man-lifting-t-bar-row-qdh2r51vmoocr8u7.html",
  "hip-thrust": "/manus-storage/hip-thrust_80b089d1.gif",
  "elevacao-pelvica": "/manus-storage/elevacao-pelvica_ac7b41a5.gif",
  "glute-bridge": "/manus-storage/glute-bridge_d7364c5f.gif",
  coice: "/manus-storage/coice_0b326a3a.gif",
  abducao: "/manus-storage/abducao_dc306907.gif",
  "agachamento-sumo": "/manus-storage/agachamento-sumo_2adf4d00.gif",
  agachamento: "/manus-storage/agachamento_5569ce45.gif",
  "leg-press": "/manus-storage/leg-press_c59660bd.gif",
  hack: "/manus-storage/hack_36dd6128.gif",
  extensora: "/manus-storage/extensora_34e09ad1.gif",
  flexora: "/manus-storage/flexora_dce1fa38.gif",
  stiff: "/manus-storage/stiff_fe027d90.gif",
  afundo: "/manus-storage/afundo_4f017c1d.gif",
  passada: "/manus-storage/passada_247a423f.gif",
  panturrilha: "/manus-storage/panturrilha_534441a8.gif",
  "puxada-frontal": "/manus-storage/puxada-frontal_6017098e.gif",
  "remada-baixa": "/manus-storage/remada-baixa_31fcefb2.gif",
  "remada-unilateral": "/manus-storage/remada-unilateral_feb98070.gif",
  "remada-curvada": "/manus-storage/remada-curvada_6ccfb294.gif",
  supino: "/manus-storage/supino_e6b3ecc2.gif",
  crucifixo: "/manus-storage/crucifixo_543e626f.gif",
  crossover: "/manus-storage/crossover_69def2fc.gif",
  "elevacao-lateral": "/manus-storage/elevacao-lateral_ccfa6019.gif",
  "elevacao-frontal": "/manus-storage/elevacao-frontal_08df8760.gif",
  desenvolvimento: "/manus-storage/desenvolvimento_4e6de706.gif",
  "rosca-direta": "/manus-storage/rosca-direta_e0362fa3.gif",
  "rosca-alternada": "/manus-storage/rosca-alternada_99315757.gif",
  "rosca-martelo": "/manus-storage/rosca-martelo_72efb3c1.gif",
  "triceps-pulley": "/manus-storage/triceps-pulley_70dedd2a.gif",
  "triceps-frances": "/manus-storage/triceps-frances_2fc9f5f7.gif",
  "triceps-testa": "/manus-storage/triceps-testa_2e3d3ded.gif",
  abdominal: "/manus-storage/abdominal_41ec89d4.gif",
  prancha: "/manus-storage/prancha_ab4633a6.gif",
  "elevacao-pernas": "/manus-storage/elevacao-pernas_2059e679.gif",
  "abducao-elastico": "/manus-storage/abducao-elastico_1956a674.gif",
  "agachamento-bulgaro": "/manus-storage/agachamento-bulgaro_c56c73cf.gif",
  "agachamento-frontal": "/manus-storage/agachamento-frontal_48f25478.gif",
  "agachamento-goblet": "/manus-storage/agachamento-goblet_cbfdb5f9.gif",
  "mesa-flexora": "/manus-storage/mesa-flexora_e807ba17.gif",
  "step-up": "/manus-storage/step-up_812dc539.gif",
  "kickback-elastico": "/manus-storage/kickback-elastico_8866ca92.gif",
  "glute-bridge-elastico": "/manus-storage/glute-bridge-elastico_b78090eb.gif",
  "good-morning": "/manus-storage/good-morning_c01c46ee.gif",
  "terra-sumo": "/manus-storage/terra-sumo_449d56e8.gif",
  "panturrilha-sentado": "/manus-storage/panturrilha-sentado_a3475445.gif",
  "panturrilha-unilateral": "/manus-storage/panturrilha-unilateral_148c05b1.gif",
  "pullover-cabo": "/manus-storage/pullover-cabo_5af61308.gif",
  "puxada-neutra": "/manus-storage/puxada-neutra_d3c50d39.gif",
  "remada-maquina": "/manus-storage/remada-maquina_ab2b2334.gif",
  "face-pull": "/manus-storage/face-pull_33b4cf76.gif",
  "supino-maquina": "/manus-storage/supino-maquina_fc5770cb.gif",
  "flexao-inclinada": "/manus-storage/flexao-inclinada_1bb83ada.gif",
  "levantamento-terra": "/manus-storage/levantamento-terra_04bec520.gif",
  flexao: "/manus-storage/flexao_fbcaa5a4.gif",
  "barra-fixa": "/manus-storage/pull-up-human_ec27400a.gif",
  polichinelo: "/manus-storage/polichinelo_019b1062.gif",

  // Demonstrações externas correspondentes ao movimento.
  "abdominal-sit-up": "https://commons.wikimedia.org/wiki/Special:Redirect/file/Situps.gif",
  "agachamento-unilateral": "https://commons.wikimedia.org/wiki/Special:Redirect/file/One-leg-squat-1.gif",
  "triceps-corda": "/manus-storage/triceps-corda_9f722dd2.gif",
  "rosca-scott": "/manus-storage/rosca-scott_55628105.gif",
  "triceps-coice": "/manus-storage/triceps-coice_21459abf.gif",
  "mergulho-banco": "/manus-storage/mergulho-banco_870597b3.gif",
  // Demonstrações específicas para variações adicionadas ao catálogo.
  "encolhimento": "/manus-storage/encolhimento_f73aa00f.gif",
  "supino-inclinado": "/manus-storage/supino-inclinado_d55507de.gif",
  "crucifixo-maquina": "/manus-storage/crucifixo-maquina_fdf7a18f.gif",
  "desenvolvimento-maquina": "/manus-storage/desenvolvimento-maquina_ab284264.gif",
  "elevacao-lateral-cabo": "/manus-storage/elevacao-lateral-cabo_5b3b780a.gif",
  "posterior-maquina": "/manus-storage/posterior-maquina_beb1eb66.gif",
  "rosca-cabo": "/manus-storage/rosca-cabo_d7deb2de.gif",
  "rosca-elastico": "/manus-storage/rosca-elastico_ba7db2e4.gif",
  "abdominal-cabo": "/manus-storage/abdominal-cabo_333c413d.gif",
  "abdominal-roda": "/manus-storage/abdominal-roda_3d9b81c4.gif",
  "dead-bug": "/manus-storage/dead-bug_a8e0f0c0.gif",
  "bird-dog": "/manus-storage/bird-dog_2291cae6.gif",
  "prancha-lateral": "/manus-storage/prancha-lateral_ff56f260.gif",
  "mountain-climber": "/manus-storage/mountain-climber_b5b0bd95.gif",
  burpee: "/manus-storage/burpee_9b2a2c0c.gif",
  "pular-corda": "/manus-storage/pular-corda_70c3ae46.gif",
  "corrida-estacionaria": "/manus-storage/corrida-estacionaria_201479cc.gif",
  "caminhada-elastico": "/manus-storage/caminhada-elastico_6bdb4979.gif",
  "levantamento-lateral-caneleira": "/manus-storage/levantamento-lateral-caneleira_0016432c.gif",
};

export const EXERCISE_IMAGES: Record<string, string> = Object.fromEntries(
  Object.entries(manuscriptImages).map(([key, url]) => [key, exerciseImageUrl(key, url)]),
);
