export const EXERCISE_MEDIA_CREDITS: Record<string, string> = {
  "barra-fixa-neutra": "StrengthLog · fonte visual (licença não informada)",
  "levantamento-terra": "VideoPlasty · CC BY-SA 4.0",
  flexao: "VideoPlasty · CC BY-SA 4.0",
  "barra-fixa": "Extremistpullup · CC BY-SA 3.0",
  polichinelo: "Wensceslao · CC BY-SA 4.0",
  "desenvolvimento-barra": "Gym visual · dataset MIT/NOTICE · uso com atribuição",
  "crucifixo-inverso": "Gym visual · dataset MIT/NOTICE · uso com atribuição",
  "remada-curvada-supinada": "Gym visual · dataset MIT/NOTICE · uso com atribuição",
  "remada-cavalinho": "Gym visual · dataset MIT/NOTICE · uso com atribuição",
  "elevacao-borboleta": "Gym visual · dataset MIT/NOTICE · uso com atribuição",
  "elevacao-lateral-frontal-elastico": "Gym visual · dataset MIT/NOTICE · uso com atribuição",
  "elevacao-frontal-elastico": "Gym visual · dataset MIT/NOTICE · uso com atribuição",
  "crucifixo-inverso-elastico": "Gym visual · dataset MIT/NOTICE · uso com atribuição",
  "desenvolvimento-elastico": "Gym visual · dataset MIT/NOTICE · uso com atribuição",
  "desenvolvimento-arnold": "Gym visual · dataset MIT/NOTICE · uso com atribuição",
  "remada-deltoide-posterior-elastico": "Gym visual · dataset MIT/NOTICE · uso com atribuição",
  "puxada-fechada-elastico": "Gym visual · dataset MIT/NOTICE · uso com atribuição",
  "puxada-supinada-elastico": "Gym visual · dataset MIT/NOTICE · uso com atribuição",
  "puxada-unilateral-polia": "Gym visual · dataset MIT/NOTICE · uso com atribuição",
  "puxada-barra-lateral": "Gym visual · dataset MIT/NOTICE · uso com atribuição",
  "puxada-barra-v": "Gym visual · dataset MIT/NOTICE · uso com atribuição",
  "pullover-barra": "Gym visual · dataset MIT/NOTICE · uso com atribuição",
  "pullover-barra-bracos-dobrados": "Gym visual · dataset MIT/NOTICE · uso com atribuição",
  "pulldown-bracos-retos-corda": "Gym visual · dataset MIT/NOTICE · uso com atribuição",
  "remada-alta-polia-v": "Gym visual · dataset MIT/NOTICE · uso com atribuição",
  "encolhimento-elastico": "Gym visual · dataset MIT/NOTICE · uso com atribuição",
  "fundos-escapulares": "Gym visual · dataset MIT/NOTICE · uso com atribuição",
  "rosca-alternada-em-pe": "Gym visual · dataset MIT/NOTICE · uso com atribuição",
  "rosca-inversa": "Gym visual · dataset MIT/NOTICE · uso com atribuição",
  "curl-inclinado-halteres": "Gym visual · dataset MIT/NOTICE · uso com atribuição",
  "rosca-concentrada-halter": "Gym visual · dataset MIT/NOTICE · uso com atribuição",
  "rosca-martelo-halteres": "Gym visual · dataset MIT/NOTICE · uso com atribuição",
  "rosca-concentrada-polia": "Gym visual · dataset MIT/NOTICE · uso com atribuição",
  "rosca-scott-barra": "Gym visual · dataset MIT/NOTICE · uso com atribuição",
  "rosca-unilateral-polia": "Gym visual · dataset MIT/NOTICE · uso com atribuição",
  "hip-thrust-elastico-ajoelhado": "Gym visual · dataset MIT/NOTICE · uso com atribuição",
  "glute-bridge-barra-banco": "Gym visual · dataset MIT/NOTICE · uso com atribuição",
  "terra-sumo-barra": "Gym visual · dataset MIT/NOTICE · uso com atribuição",
  "agachamento-frontal-banco": "Gym visual · dataset MIT/NOTICE · uso com atribuição",
  "agachamento-goblet-halter": "Gym visual · dataset MIT/NOTICE · uso com atribuição",
  "extensora-maquina": "Gym visual · dataset MIT/NOTICE · uso com atribuição",
  "sissy-squat": "Gym visual · dataset MIT/NOTICE · uso com atribuição",
  "good-morning-barra": "Gym visual · dataset MIT/NOTICE · uso com atribuição",
  "terra-pernas-retas": "Gym visual · dataset MIT/NOTICE · uso com atribuição",
  "flexora-halter-deitado": "Gym visual · dataset MIT/NOTICE · uso com atribuição",
  "nordico-assistido-polia": "Gym visual · dataset MIT/NOTICE · uso com atribuição",
  "panturrilha-halteres-em-pe": "Gym visual · dataset MIT/NOTICE · uso com atribuição",
  "panturrilha-halter-sentado": "Gym visual · dataset MIT/NOTICE · uso com atribuição",
  "panturrilha-elastico-unilateral": "Gym visual · dataset MIT/NOTICE · uso com atribuição",
  "panturrilha-burro": "Gym visual · dataset MIT/NOTICE · uso com atribuição",
};
