import { useMemo, useState } from "react";
import { ArrowLeft, ArrowRight, CalendarDays, CalendarPlus, Check, ChevronLeft, ChevronRight, Circle, Moon, Plus } from "lucide-react";
import type { BellaData, DayKey, Workout } from "../types";
import { DAYS } from "../lib/catalog";
import { Button, Card, EmptyState, Field, PageHeading, Pill } from "../components/common";

function sameDay(a:Date,b:Date){return a.getFullYear()===b.getFullYear()&&a.getMonth()===b.getMonth()&&a.getDate()===b.getDate();}
function dayKey(date:Date){return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,"0")}-${String(date.getDate()).padStart(2,"0")}`;}
export default function CalendarPage({data,onAssign}:{data:BellaData;onAssign:(day:DayKey,id:string|null)=>void}){
  const [month,setMonth]=useState(()=>new Date());
  const monthDays=useMemo(()=>{const start=new Date(month.getFullYear(),month.getMonth(),1);const offset=(start.getDay()+6)%7;const first=new Date(start);first.setDate(start.getDate()-offset);return Array.from({length:42},(_,i)=>{const d=new Date(first);d.setDate(first.getDate()+i);return d;});},[month]);
  const trainedDates=new Set(data.history.map((session)=>dayKey(new Date(session.finishedAt))));
  const today=new Date();
  return <div className="page"><PageHeading eyebrow="SEU RITMO, SUA ORGANIZAÇÃO" title="Meu calendário" description="Distribua suas rotinas ao longo da semana — e ajuste quando a vida mudar." actions={<Pill tone="neutral"><CalendarDays size={13}/> {data.workouts.length} ROTINAS</Pill>}/>
    {data.workouts.length===0?<EmptyState icon={<CalendarDays size={22}/>} title="Crie um treino para planejar sua semana." detail="Sua agenda se adapta às rotinas que você montar." action={<Button onClick={()=>window.dispatchEvent(new CustomEvent("monster-fit:new-workout"))}><Plus size={15}/> Criar treino</Button>}/>:<div className="calendar-layout"><section className="schedule-panel"><div className="section-heading compact-heading"><div><div className="eyebrow">PLANEJAMENTO FLEXÍVEL</div><h2>Minha semana</h2></div></div><div className="schedule-days">{DAYS.map((day,i)=>{const selected=data.schedule[day.key]??"";const dayWorkout=data.workouts.find((item)=>item.id===selected);const trainedToday=trainedDates.has(dayKey(new Date(today.getFullYear(),today.getMonth(),today.getDate()-((today.getDay()+6)%7)+i)));return <Card className="schedule-day" key={day.key}><div className="schedule-day-label"><span className={`schedule-day-dot ${dayWorkout?"has-workout":""}`} style={{background:dayWorkout?.color}}/>{day.label}{trainedToday&&<Pill tone="green"><Check size={10}/> FEITO</Pill>}</div><Field label="TREINO DO DIA"><select value={selected} onChange={(event)=>onAssign(day.key,event.target.value||null)}><option value="">Dia livre / descanso</option>{data.workouts.map((workout)=><option key={workout.id} value={workout.id}>{workout.title} · {workout.description||"sem descrição"}</option>)}</select></Field><span className="schedule-day-hint">{dayWorkout?dayWorkout.description||`${dayWorkout.exercises.length} exercícios`:(day.key==="dom"?"Descanse sem culpa.":"Um bom dia para recuperar.")}</span></Card>;})}</div></section>
      <aside className="calendar-month"><Card className="month-card"><div className="month-card-top"><div><div className="eyebrow">SUA VISÃO DO MÊS</div><h3>{month.toLocaleDateString("pt-BR",{month:"long",year:"numeric"})}</h3></div><div className="month-controls"><button onClick={()=>setMonth(new Date(month.getFullYear(),month.getMonth()-1,1))} aria-label="Mês anterior"><ChevronLeft size={16}/></button><button onClick={()=>setMonth(new Date(month.getFullYear(),month.getMonth()+1,1))} aria-label="Próximo mês"><ChevronRight size={16}/></button></div></div><div className="month-weekday-grid">{["S","T","Q","Q","S","S","D"].map((item,i)=><span key={`${item}-${i}`}>{item}</span>)}</div><div className="month-date-grid">{monthDays.map((date,index)=><span key={index} className={`month-date ${date.getMonth()!==month.getMonth()?"outside-month":""} ${sameDay(date,today)?"month-today":""} ${trainedDates.has(dayKey(date))?"month-trained":""}`} title={trainedDates.has(dayKey(date))?"Treino concluído":""}>{date.getDate()}{trainedDates.has(dayKey(date))&&<i/>}</span>)}</div><div className="month-legend"><span><i className="legend-today"/> Hoje</span><span><i className="legend-trained"/> Treino concluído</span></div></Card><Card className="calendar-note"><span className="calendar-note-icon"><Moon size={16}/></span><div><strong>Descansar também é treinar.</strong><p>Seus dias livres fazem parte da evolução. Ajuste sua agenda sem pressão.</p></div></Card></aside>
    </div>}
  </div>;
}
