import { useMemo, useState } from "react";
import { ArrowDownRight, ArrowUpRight, ChartNoAxesColumnIncreasing, Dumbbell, Info, Sparkles, TrendingUp } from "lucide-react";
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import type { BellaData } from "../types";
import { Card, EmptyState, Field, PageHeading, Pill } from "../components/common";

function weekKey(date:Date){const start=new Date(date);start.setHours(0,0,0,0);start.setDate(start.getDate()-((start.getDay()+6)%7));return start.toISOString().slice(0,10);}
function weeks(history:BellaData["history"]){const map=new Map<string,{week:string;treinos:number;volume:number}>();for(const session of history){const key=weekKey(new Date(session.finishedAt));const row=map.get(key)??{week:key,treinos:0,volume:0};row.treinos++;row.volume+=session.volumeKg;map.set(key,row);}return Array.from(map.values()).sort((a,b)=>a.week.localeCompare(b.week)).slice(-8).map((row)=>({...row,week:new Date(`${row.week}T12:00:00`).toLocaleDateString("pt-BR",{day:"2-digit",month:"short"})}));}
export default function EvolutionPage({data}:{data:BellaData}){
  const [selected,setSelected]=useState("");
  const history=[...data.history].sort((a,b)=>a.finishedAt.localeCompare(b.finishedAt));
  const weekly=useMemo(()=>weeks(history),[history]);
  const exerciseNames=Array.from(new Set(history.flatMap((session)=>session.performed.filter((set)=>Number(set.weight)>0).map((set)=>set.exerciseName))));
  const chosen=exerciseNames.includes(selected)?selected:exerciseNames[0]||"";
  const weights=history.flatMap((session)=>session.performed.filter((set)=>set.exerciseName===chosen&&Number(set.weight)>0).map((set)=>({date:new Date(session.finishedAt).toLocaleDateString("pt-BR",{day:"2-digit",month:"short"}),peso:Number(set.weight),volume:Number(set.weight)*(Number(set.reps)||0)})));
  const volumeAll=history.reduce((sum,item)=>sum+item.volumeKg,0);
  const thisMonth=history.filter((session)=>new Date(session.finishedAt).getMonth()===new Date().getMonth()&&new Date(session.finishedAt).getFullYear()===new Date().getFullYear());
  if(!history.length)return <div className="page"><PageHeading eyebrow="PEQUENOS AVANÇOS, GRANDES MUDANÇAS" title="Minha evolução" description="Seus gráficos se constroem com os dados reais de cada sessão concluída."/><EmptyState icon={<ChartNoAxesColumnIncreasing size={22}/>} title="Sua evolução começa com um treino." detail="Conclua sessões para visualizar sua frequência, volume total e evolução das cargas — sem estimativas ou dados inventados."/></div>;
  return <div className="page"><PageHeading eyebrow="PEQUENOS AVANÇOS, GRANDES MUDANÇAS" title="Minha evolução" description="Uma visão honesta do que você vem construindo — sessão a sessão." actions={<Pill tone="green"><TrendingUp size={13}/> DADOS REAIS</Pill>}/>
    <div className="evolution-stats"><Card className="evolution-stat-card"><span className="evolution-stat-icon rose"><Dumbbell size={18}/></span><span className="eyebrow">SESSÕES REGISTRADAS</span><strong>{history.length}</strong><small>desde o início</small></Card><Card className="evolution-stat-card"><span className="evolution-stat-icon green"><ChartNoAxesColumnIncreasing size={18}/></span><span className="eyebrow">TREINOS NESTE MÊS</span><strong>{thisMonth.length}</strong><small>mês atual</small></Card><Card className="evolution-stat-card"><span className="evolution-stat-icon lilac"><ArrowUpRight size={18}/></span><span className="eyebrow">VOLUME ACUMULADO</span><strong>{volumeAll.toLocaleString("pt-BR")} <small>kg</small></strong><small>repetições × carga registrada</small></Card></div>
    <div className="charts-grid"><Card className="chart-card chart-frequency"><div className="chart-heading"><div><div className="eyebrow">CONSISTÊNCIA</div><h3>Treinos por semana</h3></div><Pill tone="neutral">ÚLTIMAS 8</Pill></div><div className="chart-area"><ResponsiveContainer width="100%" height="100%"><BarChart data={weekly} margin={{left:-24,right:5,top:10,bottom:0}}><CartesianGrid strokeDasharray="3 5" vertical={false} stroke="var(--chart-grid)"/><XAxis dataKey="week" axisLine={false} tickLine={false} tick={{fill:"var(--text-muted)",fontSize:11}}/><YAxis allowDecimals={false} axisLine={false} tickLine={false} tick={{fill:"var(--text-muted)",fontSize:11}}/><Tooltip cursor={{fill:"color-mix(in srgb,var(--rose) 8%,transparent)"}} contentStyle={{borderRadius:12,border:"1px solid var(--line)",fontSize:12}}/><Bar dataKey="treinos" name="Treinos" fill="var(--rose)" radius={[8,8,0,0]} maxBarSize={34}/></BarChart></ResponsiveContainer></div><div className="chart-footnote"><Sparkles size={13}/> A regularidade é sua, não uma competição.</div></Card>
      <Card className="chart-card chart-volume"><div className="chart-heading"><div><div className="eyebrow">VOLUME TREINADO</div><h3>Carga total por semana</h3></div><Pill tone="neutral">KG · REAL</Pill></div><div className="chart-area"><ResponsiveContainer width="100%" height="100%"><AreaChart data={weekly} margin={{left:-20,right:4,top:14,bottom:0}}><defs><linearGradient id="volumeFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="var(--rose)" stopOpacity={.24}/><stop offset="100%" stopColor="var(--rose)" stopOpacity={0}/></linearGradient></defs><CartesianGrid strokeDasharray="3 5" vertical={false} stroke="var(--chart-grid)"/><XAxis dataKey="week" axisLine={false} tickLine={false} tick={{fill:"var(--text-muted)",fontSize:11}}/><YAxis axisLine={false} tickLine={false} tick={{fill:"var(--text-muted)",fontSize:11}}/><Tooltip contentStyle={{borderRadius:12,border:"1px solid var(--line)",fontSize:12}}/><Area type="monotone" dataKey="volume" name="Volume em kg" stroke="var(--rose)" strokeWidth={2.5} fill="url(#volumeFill)"/></AreaChart></ResponsiveContainer></div><div className="chart-footnote"><Info size={13}/> Apenas cargas registradas entram neste cálculo.</div></Card>
      <Card className="chart-card chart-lifts"><div className="chart-heading"><div><div className="eyebrow">CARGAS REGISTRADAS</div><h3>Evolução por exercício</h3></div><Field label="EXERCÍCIO"><select value={chosen} onChange={(event)=>setSelected(event.target.value)}>{exerciseNames.map((name)=><option key={name}>{name}</option>)}</select></Field></div><div className="chart-area"><ResponsiveContainer width="100%" height="100%"><LineChart data={weights} margin={{left:-20,right:10,top:16,bottom:0}}><CartesianGrid strokeDasharray="3 5" vertical={false} stroke="var(--chart-grid)"/><XAxis dataKey="date" axisLine={false} tickLine={false} tick={{fill:"var(--text-muted)",fontSize:11}}/><YAxis domain={["auto","auto"]} axisLine={false} tickLine={false} tick={{fill:"var(--text-muted)",fontSize:11}} unit={` ${data.settings.weightUnit}`}/><Tooltip contentStyle={{borderRadius:12,border:"1px solid var(--line)",fontSize:12}} formatter={(value)=>[`${value} ${data.settings.weightUnit}`,"Carga"]}/><Line type="monotone" dataKey="peso" name="Carga" stroke="#77598b" strokeWidth={2.5} dot={{r:4,fill:"#77598b",strokeWidth:2,stroke:"white"}} activeDot={{r:6}}/></LineChart></ResponsiveContainer></div><div className="chart-footnote"><Info size={13}/> Cada ponto representa uma carga que você registrou.</div></Card>
    </div>
  </div>;
}
