import { useState } from "react";
import { ArrowRight, CalendarDays, Check, Clock3, Dumbbell, History, ListChecks, Scale, Sparkles } from "lucide-react";
import type { BellaData, WorkoutHistory } from "../types";
import { Button, Card, EmptyState, Modal, PageHeading, Pill } from "../components/common";

function duration(seconds:number){return seconds < 60 ? `${seconds} s` : `${Math.floor(seconds/60)} min`;}
export default function HistoryPage({ data }: { data:BellaData }) {
  const [selected,setSelected]=useState<WorkoutHistory|null>(null);
  const sessions=[...data.history].sort((a,b)=>b.finishedAt.localeCompare(a.finishedAt));
  const byDate=sessions.reduce<Record<string,WorkoutHistory[]>>((group,session)=>{const key=new Date(session.finishedAt).toLocaleDateString("pt-BR",{weekday:"long",day:"numeric",month:"long",year:"numeric"});(group[key]??=[]).push(session);return group;},{});
  return <div className="page"><PageHeading eyebrow="CADA SESSÃO CONTA" title="Seu histórico" description={`${sessions.length} ${sessions.length===1?"treino registrado":"treinos registrados"}. Um registro do quanto você já fez por si.`} actions={<Pill tone="neutral"><History size={13}/> {sessions.length} SESSÕES</Pill>}/>
    {sessions.length? <div className="history-layout"><section className="history-list">{Object.entries(byDate).map(([day,rows])=><div className="history-day-group" key={day}><div className="history-date-label"><span className="history-date-mark"><CalendarDays size={15}/></span><span>{day}</span></div>{rows.map((session)=><button className="history-session" key={session.id} onClick={()=>setSelected(session)}><div className="history-session-icon"><Dumbbell size={17}/></div><div className="history-session-copy"><span className="eyebrow">TREINO CONCLUÍDO</span><strong>{session.title}</strong><small>{new Set(session.performed.map((item)=>item.exerciseName)).size} exercícios · {session.performed.length} séries</small></div><div className="history-session-meta"><span><Clock3 size={14}/>{duration(session.durationSeconds)}</span><span>{new Date(session.finishedAt).toLocaleTimeString("pt-BR",{hour:"2-digit",minute:"2-digit"})}</span></div><ArrowRight size={16} className="history-session-arrow"/></button>)}</div>)}</section>
      <aside className="history-aside"><Card><span className="history-aside-mark"><Sparkles size={19}/></span><div className="eyebrow">OLHE O QUANTO VOCÊ JÁ FOI</div><h3>Seu progresso mora nos detalhes.</h3><p>Abra qualquer sessão para revisitar exercícios, cargas e cada série que você concluiu.</p><div className="history-aggregate"><span>SÉRIES REGISTRADAS</span><strong>{sessions.reduce((sum,item)=>sum+item.performed.length,0)}</strong></div><div className="history-aggregate"><span>VOLUME TOTAL</span><strong>{(sessions.reduce((sum,item)=>sum+item.volumeKg,0)).toLocaleString("pt-BR")} <small>kg</small></strong></div></Card></aside>
    </div>:<EmptyState icon={<History size={21}/>} title="Seu histórico começa aqui." detail="Ao concluir um treino, ele aparecerá aqui com as séries, cargas, duração e observações registradas." action={<Button variant="secondary" onClick={()=>window.dispatchEvent(new CustomEvent("monster-fit:navigate",{detail:"workouts"}))}>Ver meus treinos <ArrowRight size={15}/></Button>}/>}
    <Modal open={!!selected} title={selected?.title??"Detalhes do treino"} eyebrow={selected?new Date(selected.finishedAt).toLocaleString("pt-BR",{weekday:"long",day:"numeric",month:"long",hour:"2-digit",minute:"2-digit"}):""} onClose={()=>setSelected(null)} wide>
      {selected&&<div className="history-detail"><div className="history-detail-stats"><span><Clock3 size={15}/><b>{duration(selected.durationSeconds)}</b> duração</span><span><ListChecks size={15}/><b>{selected.performed.length}</b> séries</span><span><Scale size={15}/><b>{selected.volumeKg.toLocaleString("pt-BR")} kg</b> volume</span></div><div className="history-detail-exercises">{Array.from(new Set(selected.performed.map((item)=>item.exerciseName))).map((name)=>{const sets=selected.performed.filter((item)=>item.exerciseName===name);return <Card className="history-detail-exercise" key={name}><div className="history-exercise-heading"><span className="exercise-check"><Check size={13}/></span><strong>{name}</strong><span>{sets.length} {sets.length===1?"série":"séries"}</span></div><div className="history-set-list">{sets.map((item,index)=><span key={`${item.exerciseIndex}-${item.setIndex}-${index}`}><b>Série {index+1}</b><small>{item.method==="Tempo"||item.method==="Isometria"?`${item.seconds}s`:item.reps} reps · {item.weight?`${item.weight} ${data.settings.weightUnit}`:"peso corporal"}</small></span>)}</div></Card>;})}{selected.performed.length===0&&<p>Este treino foi encerrado antes de registrar séries.</p>}</div><div className="modal-actions"><Button variant="outline" onClick={()=>setSelected(null)}>FECHAR</Button></div></div>}
    </Modal>
  </div>;
}
