import { useState } from "react";
import { Camera, Check, Heart, Ruler, Save, Scale, UserRound } from "lucide-react";
import type { BellaData, Goal, Profile } from "../types";
import { Button, Card, Field, PageHeading, Pill } from "../components/common";

const goals:Goal[]=["Hipertrofia","Emagrecimento","Força","Condicionamento","Manutenção"];
export default function ProfilePage({data,onUpdate}:{data:BellaData;onUpdate:(profile:Profile)=>void}){
 const [saved,setSaved]=useState(false);
 function field<K extends keyof Profile>(key:K,value:Profile[K]){onUpdate({...data.profile,[key]:value});setSaved(false);}
 async function photo(file?:File){if(!file)return;if(!file.type.startsWith("image/"))return;try{const bitmap=await createImageBitmap(file);const canvas=document.createElement("canvas");const size=Math.min(512,Math.max(bitmap.width,bitmap.height));const scale=size/Math.max(bitmap.width,bitmap.height);canvas.width=Math.round(bitmap.width*scale);canvas.height=Math.round(bitmap.height*scale);const context=canvas.getContext("2d");if(!context)return;context.drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();field("avatarDataUrl",canvas.toDataURL("image/jpeg",.76));}catch{alert("Não foi possível carregar essa foto neste dispositivo.");}}
 return <div className="page"><PageHeading eyebrow="UM PERFIL À SUA MEDIDA" title="Meu perfil" description="Conte um pouco sobre você. Essas informações ficam salvas somente neste dispositivo." actions={<Pill tone="green"><Save size={13}/> SALVO AUTOMATICAMENTE</Pill>}/><div className="profile-layout"><Card className="profile-identity"><div className="profile-photo-wrap"><div className="profile-photo">{data.profile.avatarDataUrl?<img src={data.profile.avatarDataUrl} alt="Foto de perfil"/>:<span>{(data.profile.name||"B").slice(0,1).toUpperCase()}</span>}</div><label className="profile-photo-edit" title="Alterar foto"><Camera size={15}/><input type="file" accept="image/*" aria-label="Carregar foto de perfil" onChange={(event)=>photo(event.target.files?.[0])}/></label></div><span className="eyebrow">SUA JORNADA, SUA IDENTIDADE</span><h2>{data.profile.name||"Monster Fit"}</h2><p>{data.profile.email}</p><div className="profile-goal-chip"><Heart size={14} fill="currentColor"/> {data.profile.goal}</div><small className="profile-local-note">Sua foto é reduzida e armazenada localmente.</small></Card>
 <section className="profile-form-area"><Card className="profile-form-card"><div className="profile-form-heading"><div><div className="eyebrow">ESSA É VOCÊ</div><h3>Suas informações</h3></div><UserRound size={18}/></div><div className="profile-form-grid"><Field label="Nome"><input value={data.profile.name} onChange={(event)=>field("name",event.target.value)} placeholder="Seu nome" autoComplete="name"/></Field><Field label="E-mail"><input value={data.profile.email} readOnly aria-readonly="true"/><small>O e-mail da conta local não pode ser alterado.</small></Field><Field label="Idade"><input type="number" min="13" max="120" value={data.profile.age} onChange={(event)=>field("age",event.target.value)} placeholder="—"/></Field><Field label="Altura (cm)"><span className="input-with-icon"><Ruler size={14}/><input type="number" min="80" max="250" value={data.profile.heightCm} onChange={(event)=>field("heightCm",event.target.value)} placeholder="Ex.: 165"/></span></Field><Field label="Peso (kg)"><span className="input-with-icon"><Scale size={14}/><input type="number" min="25" max="350" step="0.1" value={data.profile.weightKg} onChange={(event)=>field("weightKg",event.target.value)} placeholder="Ex.: 62,5"/></span></Field><Field label="Seu objetivo"><select value={data.profile.goal} onChange={(event)=>field("goal",event.target.value as Goal)}>{goals.map((goal)=><option key={goal}>{goal}</option>)}</select></Field></div><div className="profile-footnote"><span><Check size={14}/> As alterações são salvas automaticamente enquanto você edita.</span><Button variant="outline" size="sm" onClick={()=>setSaved(true)} disabled={saved}>{saved?<><Check size={14}/> TUDO CERTO</>:"ENTENDI"}</Button></div></Card><Card className="profile-motivation"><span className="motivation-mark">b.</span><div><div className="eyebrow">NÃO SE ESQUEÇA</div><strong>Sua jornada é única.</strong><p>Use esses dados como referência pessoal, não como medida de valor.</p></div></Card></section></div></div>;
}
